Targets:
  PXBoardQP4G:
    Name: PXBoardQP4G
    TargetImage: assets/images/PXBoardQP4G-latest.img
    SkipUpdate: False
    Assets:
      BaseImage:
        path: assets/images/PXBoardQP4G-latest.img
        url: https://s3-us-west-1.amazonaws.com/pxlinux/LATEST/PXBoardQP4G-latest.img.zip

#  PXBoardQ:
 #   Name: PXBoardQ
 #   TargetImage: assets/images/PXBoardQ-latest.img
 #   SkipUpdate: False
 #   Assets:
 #     BaseImage:
 #       path: assets/images/PixieQCoreImage-2019-01-25.img
 #       url: https://code-ing.com/pixierepo/release/images/latest/PixieQCoreImage.zip

 # PXBoardDL:
 #   Name: PXBoardDL
 #   TargetImage: assets/images/PXBoardDL-latest.img
 #   SkipUpdate: False
 #   Assets:
 #     BaseImage:
 #       path: assets/images/PixieDLCoreImage-2019-01-25.img
 #       url: https://code-ing.com/pixierepo/release/images/latest/PixieDLCoreImage.zip

BuildCommand:
  cmd: helper_scripts/build_img.sh
  params:
    - BaseImage
    - TargetImage
    - U-Boot
    - RootFS
    - Packages
    - Scripts
